NEVISACCESSAPP-4939: update xcode and swift version
nevissecurity/nevis-mobile-authentication-sdk-example-app-ios-rx pull request #12
Opened 2023-08-01 15:31 UTC by daniel-toth-leeder

- Updated macos runners to 13 and xcode version to 14.3.1 in all workflows.
- Updated swift version to 5.8 in swiftformat.

2023-08-01 18:09 UTC, viktor-gulyas approved these changes

2023-08-02 07:24 UTC, tamas-toth commented
The swiftformat file was not updated.

2023-08-02 07:25 UTC, tamas-toth requested changes
The swiftformat file was not updated.

2023-08-02 08:03 UTC, tamas-toth approved these changes

2023-08-02 08:13 UTC, merged